### ISSUE TITLE
[feature] colorize hud elements in automap

### ISSUE THREAD

**Issue by liPillON** [MrAlaux/Nugget-Doom#10]
I've opened this issue upstream and I'm opening it here too, in case it won't make the cut for Woof's upcoming 10.0 release.

In automap, displaying stats/time values in a different color than their labels would be a nice qol feature. Currently all elements are red, the only exception being the map name in yellow.

Crispy provides this as one of the preset for the "colorize hud elements" option.

Would it possible to implement this in Nugget, or would you prefer keeping the codebase synchronized with Woof?
Thank you!

**Comment by MrAlaux** [comment]
> ... in case it won't make the cut for Woof's upcoming 10.0 release.

A new Woof release doesn't necessarily mean that I'll make a new release too, although I have indeed been waiting for Woof 10's release to do it. Even then, my releases don't have to be huge either. The upcoming Woof release alone has many more commits than Nugget ever since it was forked. I could very well wait (or not) until the upstream implements the change, merge it and then release a new version.

> ... would you prefer keeping the codebase synchronized with Woof?

That's not even remotely a problem, I have to deal with conflicts every time I merge the upstream and deliberately keep things the way I want them in spite of it.

Now, regarding your request, I'd gladly do it... if I could figure out how it works. No luck with that yet, so we'll most likely have to wait until those who know get it done.

**Comment by MrAlaux** [comment]
Fixed by 26e067a4b1ece52c99fe479e7056cbaa4a0f4d6f.
