### ISSUE TITLE
My resolution is not listed

### ISSUE THREAD

**Issue by snekyo** [MrAlaux/Nugget-Doom#114]
I use a 2560 x 1440 monitor. The in-game resolution selection won't let me select it, and the 'native' option is still not 2560 x 1440.
![image](https://github.com/user-attachments/assets/3dd598e7-6120-4a94-ba06-72a51d76f280)

**Comment by MrAlaux** [comment]
With regards to height, the screen has aspect-ratio correction applied, which stretches pixels by 1.2x, turning 1200 into 1440 -- nothing wrong here. The "current resolution" text is a feature that I added, and I decided to disregard said correction in the calculation because it'd arguably be a lie.

As for width, I'm not entirely sure why it's off like that. You may want to try the latest Woof autobuild, enabling `IDRATE` to see the current resolution (should work just like Nugget's text); if it's still off, feel free to open an issue there to ask about it.

**Comment by MrAlaux** [comment]
We got an answer from one of the Woof devs:

> It might be worth renaming “Native” to “Maximum” like in the Kex port. Because of aspect ratio correction and integer arithmetic, it's impossible to get a “correct looking” image and perfect resolution. We also wanted the “dynamic resolution” feature not to be too distracting, so we sacrificed the accuracy of the calculations.
