### ISSUE TITLE
Nugget HUD customization thoughts/suggestions

### ISSUE THREAD

**Issue by seascape** [MrAlaux/Nugget-Doom#122]
I've been checking out the NUGHUD lump's customization features trying to make a more minimal HUD and it's been pretty cool. Here are some thoughts / questions that've come up so far.

1. If both present, does NUGHUD lump take precedence over WOOFHUD lump? Seems so? Perhaps add a "WOOF! HUD" choice to the in-game HUD selection menu to let the user pick which one's used.

2. I would really like a toggle to allow the `armor` element to turn invisible when armor level is 0%. GZDoom does this for example. 

3. Tried using the health box patch (`patch1_name "MEDIA0"`) but it feels too large on the screen; made me wonder if the ability to scale elements down would be helpful. (Maybe the uneven downscaling would be too ugly...) If scaling isn't in the cards users like me could create a custom gfx asset to resolve this.

4. `ammo` turns into the berserk pack icon when berserk fist is selected, but it seems impossible to adjust its alignment independently from the numerical ammo count this element normally displays. In my case I wish I could make the berserk pack icon right-justified within this element so it has the same rightmost pixel edge as the rightmost ammo digit. Also, its bottom edge dips lower than the ammo digits' -- I would rather the icon's bottom edge share the same one as the digits. In short, it would be nice to be able to adjust the ammo berserk pack icon's placement in relation to `ammo`'s ammo digits.

5. ~I've been designing for 4:3 but it'd be nice to have elements transition to widescreen when widescreen is enabled. `wide  -1` and `wide  1` don't seem to be doing that so far; is it because their elements have fixed pixel coords via `_x` and `_y`? (`wide  -2` and `wide  2` certainly move the elements to the widescreen edges, but then they're wrong in 4:3.)~ Ah, the problem was that widescreen HUD mode had to be explicitly enabled in the menus.

6. It'd be neat if there was a toggle to make `arms#` elements only display when the corresponding weapon is owned. In other words the gray `arms#` numbers would never appear, only the yellow ones would.

7. Could be nice from a HUD development friendliness standpoint if commenting out an element actually removed it from the HUD temporarily. (An alternative to `_x -1`.) One practical reason: Having to erase `_x` values erases a useful coordinate I'll often need to refer back to.

8. Minor: `ammoicon` feels limited in functionality to me since the rocket ammo is a completely different shape (vertical, tall) than the other three patch graphics. This aesthetic problem exists in GZDoom as well but I guess it never bothered me because I wasn't trying to edit the HUD there, hehe.

9. Minor: Odd that `nughud_ammo2` is cells and `nughud_ammo3` is rockets. Maybe there are behind-the-scenes code reasons. Just for editing reasons it'd be nice if they were visually reordered to the more normal rockets -> cells in the default NUGHUD lump.

Just for reference here is where I'm at so far:
![nugg0000](https://github.com/user-attachments/assets/0e5485ee-a27c-433f-bb40-37aead8a5396)
The central `arms#` bit is the only part I'm not sure I like.

**Comment by MrAlaux** [comment]
1\. You may notice a _HUD Type_ setting in the _Status Bar/HUD_ menu, whose options are _Nugget_, _Boom_ and _Boom (No Bars)_. NUGHUD only affects the first, whereas WOOFHUD affects the Boom ones, so there's not really a priority in play; it depends on which HUD type is selected by the end user.

2\. I don't think I'll make it vanishable, but maybe.

3\. Some have suggested/requested scaling already; I don't really know how to do that, though it's been implied that Woof will support HUD scaling at some point, so we might get it then. As the documentation specifies, you can absolutely use custom graphics, like many NUGHUDs do already; you could provide a graphic named e.g. `MYMEDKIT` and use it in your NUGHUD. Unfortunately, it won't be automatically converted to whatever palette you're using, so it will look wrong with some WADs, but Woof's upcoming support for loading and palettizing PNGs should solve that.

4\. It isn't possible to adjust the alignment of the Berserk graphic as of now, but you can provide a `NHBERSRK` graphic to be used in place of it, whose alignment (i.e. the offsets of the graphic itself) can be tweaked freely.

6\. As detailed in the documentation, you can provide custom graphics for the Arms numbers that won't affect the vanilla status bar, making empty graphics for unavailable weapons and visible graphics for available ones: see [here](https://github.com/MrAlaux/Nugget-Doom/blob/master/docs/nughud.md#custom-fonts). Same palettization caveat as in question 3.

7\. The lump works by applying modifications to an existing built-in NUGHUD, so skipping values in the lump you load simply means that they're not modified (that is to say, you _don't_ have to include every single element in your custom NUGHUD). Changing that would be a bit difficult, and I have to consider compatibility with existing NUGHUDs.

8\. That's precisely why I added support for both horizontal and vertical alignment. If that's not enough, you can also provide custom graphics for that element; see the link in question 6.

9\. I used that order because it's what the existing underlying code uses. I should've been able to make it so that they follow the visible order, but I didn't, and changing it now is a compatibility concern.

**Comment by seascape** [comment]
Thanks for the helpful replies. I have taken advantage of five of the custom font categories now and quite like where this is headed.

![nugget-doom 2024-10-26 23-43-08](https://github.com/user-attachments/assets/92f57552-f5f1-41ea-9b85-4e7ca0928dd9)

I really appreciate that the custom font assets don't affect the regular status bar, should the player wish to switch to that (or see it on the automap screen).

The main aesthetic blemish now is the 0 that sticks around when the player has no armor:

![nugget-doom 2024-10-26 23-38-46](https://github.com/user-attachments/assets/d4959f61-4a5a-4321-b436-f9478a378f93)

If you decide to implement hiding that after all, you'll have at least one very pleased user, hehe.

Also pondering if I should squeeze the left numerical elements downward as much as possible so they don't overlap with the overlay automap's level name and level stats. Seems like that'd crowd the numbers a bit too much though. Going to check if someone's made an ever-so-slightly shorter health/ammo number font that'd look just about vanilla there.

**Comment by MrAlaux** [comment]
> Also pondering if I should squeeze the left numerical elements downward as much as possible so they don't overlap with the overlay automap's level name and level stats. Seems like that'd crowd the numbers a bit too much though.

Why not move the level name and stats?

**Comment by seascape** [comment]
I figured that would move them for the regular status bar as well? I didn't think any changes I made to their placement would be limited in context to the NUGHUD mode. If they are, then great.

**Comment by MrAlaux** [comment]
> I figured that would move them for the regular status bar as well? I didn't think any changes I made to their placement would be limited in context to the NUGHUD mode. If they are, then great.

The NUGHUD lump affects the "Nugget HUD" exclusively, simple as. The vanilla status bar and the Boom HUD should remain completely unaffected.

**Comment by seascape** [comment]
Works great! 🤙

**Comment by MrAlaux** [comment]
I don't think I'll be working on any of the "pending" suggestions from this issue, namely patch scaling and hiding the armor count.

The current master branch features support for SBARDEF, which is basically the KEX port's NUGHUD equivalent; albeit tedious, you should be able to fully recreate the HUD seen in the screenshots with it, and even hide the armor count. You may want to try it.

**Comment by seascape** [comment]
Yes! I am awaiting the SBARDEF editor one of the devs is working on. Looks promising? Hopefully we won't lose any current WOOFHUD features.

**Comment by MrAlaux** [comment]
> Hopefully we won't lose any current WOOFHUD features.

I think the bars are gone, with no practical way to recreate them, and dynamic widget positioning (like NUGHUD's stacks) is possible but much more tedious to achieve.
