### ISSUE TITLE
[Crash] Necromantic Thirst (RC1)

### ISSUE THREAD

**Issue by ak-988** [MrAlaux/Nugget-Doom#124]
https://www.doomworld.com/forum/topic/149103-necromantic-thirst-rc1/

This WAD crashes Nugget at startup before the "P_Init: Init Playloop state" message can appear for me on Windows 10, although current Woof! loads it. Nugget 2.3.1 is the last version to successfully load this WAD.

**Comment by MrAlaux** [comment]
The WAD has this marker lump between the `C_#` markers, which are for colormaps:
![imagen](https://github.com/user-attachments/assets/1de39290-bf93-4c14-896e-ef47f883c1c3)

Both Woof and Nugget load this marker as if it were a colormap, but only Nugget tries to modify it (alongside all other colormaps) to overwrite the 34th row with the night-vision effect, which is what causes the crash since it tries to read from and write to a null pointer. I'd say that this is a bug with the WAD, but I'll probably apply a little patch to guard against it anyways.
