### ISSUE TITLE
[Feature Request] PSXDoom style arms display and weapon select binds

### ISSUE THREAD

**Issue by ghost** [MrAlaux/Nugget-Doom#13]
PSX Doom separates the SSG from the regural shotgun to use the 4th slot instead of the 3rd, it also indicates your currently selected weapon
![Screenshot_20221010_004448](https://user-images.githubusercontent.com/68514898/194783043-ac2385dd-7431-4f7b-8ee3-368be680e39b.png)
I would love to have this feature in this port!

**Comment by MrAlaux** [comment]
About the current weapon highlight, I don't think it can be done without adding a new graphic to the executable, and even then it might not look good with custom status bars.

As for the separate SSG display, that's more or less what _Alternative Arms Display_ does. Another option is to try to change the Arms display based on your key bindings for weapon selection, but I believe it'd be too complicated for a seemingly niche feature.

**Comment by ghost** [comment]
then just a feature to have alternative PSX Doom style binds+psx style alternative arms display would be great. 
As in 3rd slot only selecting regular shotgun and 4th only selecting the ssg and pushing the rest of the guns out by one slot,

I often play PSXDoom and I like this implementation of the Armoury because of the fact that the regular shotgun fuctions as a sniper rifle while the ssg does not. work beyond 10 meters (+muscle memory from psxdoom makes me select the chaingun instead of the ssg every time)

**Comment by MrAlaux** [comment]
You can change the weapon binds as desired in the Key Bindings setup screen.

There's a config variable in the .cfg file called _"doom_weapon_toggles"_ which makes it so that the Shotgun and Fist keys can't also select the SSG and Chainsaw respectively, although that brings me a question: how do you select the Chainsaw in PSX Doom? Does it share its slot with the Fist? Regardless, it should work for the SG/SSG case.

I repeat what I said about the Alt. Arms Display: the feature appears to be niche and its implementation might not be very straightforward.

**Comment by MrAlaux** [comment]
Well, I'll sum it up: weapon binds can already be changed as you see fit, disabling _"doom_weapon_toggles"_ should make weapon selection resemblant to PSX Doom, and as a byproduct of the newly added "Nugget HUD", the Crispy HUD now shows 8 arms numbers instead of 6, albeit starting from 2 instead of 1.

The remaining fine-tuning is not planned for now.
