### ISSUE TITLE
[Feature Request/bugfix/change] Prevent the demo from starting in the main menu when the menu is open

### ISSUE THREAD

**Issue by ghost** [MrAlaux/Nugget-Doom#17]
Whenever I want to edit settings while still being in the main menu or just want to sit there after i pressed an "end game" the fact that a demo will start  no matter what i do gets annoying real quick, especially considering the fact that the demos are broken too just by the fact alone that the default comp level on woof/nugget-doom is MBF21

**Comment by MrAlaux** [comment]
Unrelated to the request, but can you confirm that demos are indeed broken? I myself have my default complevel set to MBF21, yet Doom 2's demos play fine, but you might be talking about PWAD demos.

**Comment by ghost** [comment]
it's the doom2 iwad demos. They are fully broken for me when I'm on MBF21. I run 0 gameplay changing pwads with the game, only custom sprites made by me

**Comment by MrAlaux** [comment]
Are you experiencing the desync issues with the latest master of Nugget? The last _release_ has desync issues specifically with WAD demos (Doom 2's demos for example), related to Nugget's own features and not the complevel. Said issues should be fixed in the latest master.

**Comment by ghost** [comment]
Please extend this feature by making so that the demos pause when the game menu/options menu is up. already started demos are still problematic when they are keep on playing regardless

**Comment by MrAlaux** [comment]
Regarding your last request, I forgot there's a dedicated Pause key, apart from the key that brings up the menu.

Pause should be bound to, well, the Pause key on your keyboard. It doesn't work on menus while _you_ are playing (makes sense, since the game is paused already), but it does work during playback of at least internal demos, and even before they start playing, menu open or not. This renders ea17216f9bb46302b41f3db45fccdaed512af907 mostly trivial, but I guess I can keep it for now.
