### ISSUE TITLE
[feature request] The option to turn off the ugly rock texture and a have it translucent when using widescreen with the classic hud

### ISSUE THREAD

**Issue by ghost** [MrAlaux/Nugget-Doom#26]
![image](https://user-images.githubusercontent.com/68514898/196556597-bb27bdcf-c86d-49e0-aba3-ded09efaddbd.png)

**Comment by MrAlaux** [comment]
Just a reminder: there's an option to use a solid-color background instead of the rock texture.

**Comment by liPillON** [comment]
I've tried to create a translucent STBAR using the new NUGHUD features.

To replicate 100% of the stock statusbar feature we would need to be able to:
- force the use of the classic 2-7 weapon slots only
- conditionally draw the STARMS patch on top of the STBAR


[nughud-stbar.zip](https://github.com/MrAlaux/Nugget-Doom/files/9846125/nughud-stbar.zip)

![nughud-stbar](https://user-images.githubusercontent.com/48625273/197384530-217f6c5e-f2f2-403c-adf4-5b0faaa63b0f.png)

**Comment by MrAlaux** [comment]
As stated in `nughud.txt`, widgets can be disabled by setting their X position to -1. Should work in the case of Arms numbers 8 and 9.

Implementing a special condition to draw the Arms background when not on Deathmatch will most likely not be worked on anytime soon. After all, I expect users to deviate from the standard Status Bar. Now, if you're talking about drawing STARMS on top of STBAR, that should be possible by simply using the following Patch (Patch 1 should be drawn under Patch 2 and so on).

Finally, I'd like to point out what I consider to be an issue with your HUD: the vertical position of the weapon. It's much more obscured than it'd normally be. Of course, that's not your fault, you can't do much about it without running into conflicts with the non-fullscreen screen sizes (i.e. the ones that come before the Nugget HUD). I'll see if I can do something about it.

**Comment by liPillON** [comment]
Yeah the weapon being partially obstructed by the statusbar was an issue I was familiar with, having worked on a bunch of zdoom and prboom huds in the past.

Regarding arms indicators: hiding them has no effect on how they behave, so the SSG will always highlight no.9 regardless. 

In general, this was just a test to see what can be done to approximate what OP wanted and I totally get the point your making: NUGHUD has been designed to enable users to create **custom fullscreen** huds, after all...

In the end, what I've pointed out does not concern me that much, as what I'm planning to do with NUGHUD is not affected by it.

Thanks again for your work on this!

**Comment by liPillON** [comment]
OK I've made some tweaks and this is the best approximation currently possible.
Considering what has been said about the arms/frag widgets behaviour, this wad is intended for SINGLEPLAYER ONLY.


[nughud-stbar.zip](https://github.com/MrAlaux/Nugget-Doom/files/9846412/nughud-stbar.zip)

![nughud-stbar](https://user-images.githubusercontent.com/48625273/197389520-70287622-1586-44f9-83af-e561ab724006.png)

**Comment by MrAlaux** [comment]
The frag count could be very well placed over the right end of the Status Bar, it doesn't necessarily need a background.
EDIT: Sorry, I may've misunderstood. I realized that even in the Nugget HUD, the Arms and Frags widgets are not drawn simultaneously. I'm going to change that.

In other news, you can now adjust the vertical position of weapons when using the Nugget HUD: d437b787c17c93aba887b0754ca921e0e605c525. It'll still look a bit off, though, since the game world is rendered in a way that fills up the whole screen space.

**Comment by MrAlaux** [comment]
Alright, Arms and Frags _are_ now drawn simultaneously: 681fdabda854d7b1a0c8cc22b8108896fdf25b53.

Something else I should mention: the fact that Arms number 3 doesn't highlight when you pick up the SSG is actually vanilla behavior. I simply ported a feature from Crispy Doom that does make it highlight when you pick up either type of shotgun.
Implementing such feature for NUGHUD implies not only doing the code, but adding yet another variable to the NUGHUD lump just for it. As I said, I expect HUDs made with this to be fairly different from the Status Bar, hopefully different enough so that all 8 available Arms numbers can fit.
Also, I'd say Arms number 8 is a rather uncommon addition. While Crispy did make it so that number 3 is highlighted when picking up the SSG too, it doesn't do that for the Chainsaw, probably because the original Arms widget doesn't feature a number 1, and neither does the NUGHUD.

**Comment by liPillON** [comment]
thank you for fine-tuning this

I've updated the "Fullscreen Statusbar" proof-of-concept to take advantage of the weapon offset setting, and I've also made a few other custom layouts.
They all can be found in the attached archive: feel free to use them to showcase the feature.


[nughud-poc.zip](https://github.com/MrAlaux/Nugget-Doom/files/9851847/nughud-poc.zip)



![NugHud-Classic](https://user-images.githubusercontent.com/48625273/197533023-26a216fd-f45b-4599-a6e8-9b2521a5b72a.png)

![NugHud-Crispy](https://user-images.githubusercontent.com/48625273/197533028-a2e5251b-40c9-4da7-abbd-9b0649984eaa.png)

![NugHud-Modern](https://user-images.githubusercontent.com/48625273/197533029-ec46719d-08ef-4fbb-bc4b-5ea970aad652.png)

![NugHud-Stacked](https://user-images.githubusercontent.com/48625273/197533031-2f13ca1a-e0c1-423b-a888-9d8dcafea65a.png)

**Comment by MrAlaux** [comment]
Well, I consider this a good enough solution to the original request.

**Comment by ghost** [comment]
@liPillON  thanks for fine making it!

**Comment by TheDwellerInDarkness** [comment]
@liPillON I just wanted to say thank you for making these HUDs, Alaux pointed me to them a few hours ago and I think they're great
