### ISSUE TITLE
(feature request) 64 bit binary

### ISSUE THREAD

**Issue by tomatothesaddo** [MrAlaux/Nugget-Doom#32]
I'm not sure whether or not 64 bit is supported, but if it is, an x64 binary would be very appreciated

**Comment by MrAlaux** [comment]
I think it's safe to say that 64-bit _is_ supported; there's at least one autobuild (see the repo's Actions tab) that generates a 64-bit binary. Having it generate those builds at will to distribute them with new releases, however, is not as simple as I'd like it to be, and from what I know I'm the only one who can download them straight from the Actions tab, not sure if I can change that. I've another method which is the release workflow triggered upon making a new release, which provides both binaries automatically, but I'm not used to it and honestly I would like to keep that under my control.

I'll see if I can set up my machine to be able to generate those binaries myself.

EDIT: Turns out the fellow volunteer that tried to download those artifacts (the autobuilds) wasn't logged in with a GitHub account, which is the requirement to be able to download them. In that case, you _should_ be able to download them. I repeat: that's done from the Actions tab. Let me know if you need further instructions.

**Comment by tomatothesaddo** [comment]
ah thanks!

**Comment by MrAlaux** [comment]
Well, it appears I've indeed succeeded at generating a 64-bit binary, as you may notice in the [latest release](https://github.com/MrAlaux/Nugget-Doom/releases/tag/nugget-doom-1.12.0). From now on I should be able to provide them myself, just like I wanted to.
