### ISSUE TITLE
"Enemies" settings will sometimes be editable, other times not, when complevel is used

### ISSUE THREAD

**Issue by Mabadman** [MrAlaux/Nugget-Doom#39]
Note; This is from the latest release build of Nugget Doom as I do not know how to build it on my own.

When using -complevel, if you open the "enemies" settings right after launching the game you will find that the settings are editable. They will become uneditable after a few seconds (with the save icon briefly flashing on the bottom right corner).
Once a new game is started and a map is loaded, these settings will become editable again.
If "end game" is selected to exit back into the menu screen, the settings will remain editable for a few seconds like before.

Complevel 21
https://user-images.githubusercontent.com/42493726/224444737-17023c82-7aa8-489b-823d-84233731b57b.mp4

Complevel 2
https://user-images.githubusercontent.com/42493726/224444771-0753676c-c9a7-4dad-824c-44f9253255b3.mp4

**Comment by MrAlaux** [comment]
I'm pretty sure this is happening because a demo starts playing in the background. The two settings that are editable in cl2 (Extra Gibbing and Bloodier Gibbing) are intentionally forcefully disabled during demos, and the rest of settings are available in cl21 but become unavailable during demo playback, either because the demo that's playing runs under another complevel (most likely cl2 in this case) or because you're not meant to toggle them during demos, regardless of complevel.

**Comment by MrAlaux** [comment]
@Mabadman any comments? Any other inquiries on the topic? If not, I'll close the issue soon.

**Comment by Mabadman** [comment]
Nothing, thanks for the response.
