### ISSUE TITLE
Things Over Things clipping issues

### ISSUE THREAD

**Issue by MrAlaux** [MrAlaux/Nugget-Doom#48]
Sometimes, a thing will move vertically into another thing, causing them to get stuck in each other. This might also be causing some instant lifts to malfunction.

Needs further testing.

**Comment by kitchen-ace** [comment]
Since I've started using Nugget Doom, I've found that the things over things setting frequently causes problems for me, to the point where I have disabled it. Which is too bad, because it's one of the features I really wanted in Woof for casual play. Things like lost souls getting stuck in me when spawned from a pain elemental and then non-stop attacking until I die, various monster pop-ups breaking for one reason or another, or clusters of barrels exploding on moving floors doing unintended things. 

I think if you're going for this approach where any things can pass over/under each other, you'll need some more robust checks. Even Crispy Doom's version where only the player can walk over/under things has ended up requiring several changes to handle over the years, and it's still not perfect.

Was the change so that all things could pass over/under each other something you wanted yourself, or was it a user-requested feature?

**Comment by MrAlaux** [comment]
It was my choice to extend it. Save for the issue regarding barrels that you described (what's up with that?), I'm already aware of the problems it has, and unfortunately I haven't been able to figure them out yet.

I think DSDA-Doom might have its own implementation of such a thing (hopefully not player-only); I should take a look at it, perhaps it works around these issues somehow.

If it is of any use, I personally resort to crouching when Lost Souls get stuck inside me. No workarounds for the rest of issues, though.

**Comment by kitchen-ace** [comment]
DSDA-Doom doesn't have anything like that (for Doom), other than walking under solid hanging body decorations.

Eternity does, I haven't used it enough to know how robust it is against the issues mentioned.

Of course ZDoom, and Heretic/Hexen/Strife, all let you walk over things but the changes to the code are pretty extensive there.

**Comment by MrAlaux** [comment]
All I know about DSDA's implementation is that it has to do with some `(No)Passover` map flags in `MAPINFO`, surely related to UDMF support (don't take my word for it, though). Perhaps the changes are unavailable as an Options setting, or they're not in the latest release, or both.

**Comment by kitchen-ace** [comment]
My bad, you're right that it's an option for MAPINFO, intended for UDMF. Only in the current git version, I think.

The current implementation looks pretty minimal/possibly unfinished but I didn't look through the code that much. It's possible it just inherits the behaviour from Heretic/Hexen even?

**Comment by MrAlaux** [comment]
> It's possible it just inherits the behaviour from Heretic/Hexen even?

Looks like it. There's also some code used specifically for a "ZDoom map format" or something like that.

**Comment by MrAlaux** [comment]
@kitchen-ace, could you please list some occurrences of broken "monster pop-ups"? I tried to make some myself but I couldn't make them break.

**Comment by kitchen-ace** [comment]
In general I think it happens when there are already flying monsters over the pop-up area. The most recent one I had was on [Literalism](https://www.doomworld.com/idgames/levels/doom2/Ports/megawads/literalism) MAP18, there's a bunch of revenants in the floor if you walk towards the cavern, and sometimes they wouldn't come up. It's not consistent though, but when I turned off things over things it never happens. (Chaotic start and hard map FYI).

Another example is in the map [YouDoVoodoo](https://www.doomworld.com/forum/topic/140920-youdovoodoo-boom-a-single-map-of-utmost-chaos/), there are walls you're supposed to "break" with rockets, these totally didn't work with things over things on. (The floors that are supposed to raise don't do so properly.) It's a popup with exploding barrels.

If you'd like I can try to put together a "test suite" of a few examples where Nugget's implementation of things over things causes problems, sometime in the next week. (Would be interesting to see how they compare in GZDoom as well.)

**Comment by MrAlaux** [comment]
Thanks for the examples!

> If you'd like I can try to put together a "test suite" of a few examples where Nugget's implementation of things over things causes problems, sometime in the next week. (Would be interesting to see how they compare in GZDoom as well.)

Maybe later. I wanted to find occurrences of the bug to see if they persist with DSDA's implementation, which I plan to try implementing into a test branch soon. In any case, thanks for the offer.

**Comment by MrAlaux** [comment]
Alright @kitchen-ace, I think the [test branch](https://github.com/MrAlaux/Nugget-Doom/tree/new_over_under) is ready for you to try. I assume you can build from the source, but if not, let me know and I'll make a PR so that autobuilds are generated.

EDIT: I tested what's presumably the first breakable wall of YouDoVoodoo against the old and new `over_under` implementations, and it seems to work properly with the latter.

**Comment by kitchen-ace** [comment]
I will get to this soon. I do know how to compile from source, thanks.

**Comment by kitchen-ace** [comment]
So I think this is an improvement, but there are still some problems, which I can't reproduce in the mainline version of Nugget. Mainly groups of flying things seem to get stuck together on level geometry. Here's an example from Sunder MAP08, all these cacos pictured can't move.

![nugg0003](https://github.com/MrAlaux/Nugget-Doom/assets/47063032/d3cddf7a-94fe-4860-a9d4-7836e04c2741)

Here's another one from [The Parasite of Goodwill RC1](https://www.doomworld.com/forum/topic/141192-the-parasite-of-good-will-cl9-rc1/), with light cheat enabled. Again all the flyers are stuck. (interesting spooky map, don't spoil it for yourself if you think you might want to play it :) )

![nugg0002](https://github.com/MrAlaux/Nugget-Doom/assets/47063032/98a986fe-b167-44fc-aa33-0d71d9210d36)

On the plus side the UDUVUDU walls do work properly, and I haven't had any luck screwing up pop-up closets yet, though I haven't thoroughly tested the latter problem.


edit: One thing I noticed looking through the Heretic and Hexen sources is that flying enemies have special behaviour coded to not allow them to pass over/under each other. They can still pass over ground enemies, and the player can pass over anything even when flying.

**Comment by kitchen-ace** [comment]
Just making sure you saw my previous post on this since you haven't replied yet. No worries if you've been busy or whatever. I should probably make a kind of test suite thing soon anyhow.

**Comment by MrAlaux** [comment]
I saw it, yes. I've indeed just been busy working on other stuff (also just messing around, as you may tell from the voxels stuff over on DW), and I'm not entirely sure of how to fix the issue with "flyers" anyways -- at least not right away. I might pick this up again soon.

**Comment by MrAlaux** [comment]
I've taken a look at this again. Some notes:

I put together a little map with some columns and cacos to reproduce the issue you reported: indeed, some get stuck in each other.

I tested the same map with DSDA 0.27.4, setting `Passover` in `MAPINFO`, and it seems to have the same issue. Then again, DSDA's code branches a bit according to map format and maybe some other conditions, so there's a chance that the code path being taken isn't equivalent to Nugget's implementation.

**Comment by MrAlaux** [comment]
@kitchen-ace, I may've just solved it. Same branch as before; could you give it a shot again?
