### ISSUE TITLE
native res

### ISSUE THREAD

**Issue by KABOM93** [MrAlaux/Nugget-Doom#89]
add real native res like in woof pls

**Comment by MrAlaux** [comment]
As stated yesterday back in Woof's repo, Nugget already has native resolution, we're just missing a "proper" release. Go [here](https://github.com/MrAlaux/Nugget-Doom/actions/runs/8170407332) and scroll down to get an autobuild with the latest features.

**Comment by KABOM93** [comment]
> As stated yesterday back in Woof's repo, Nugget already has native resolution, we're just missing a "proper" release. Go [here](https://github.com/MrAlaux/Nugget-Doom/actions/runs/8170407332) and scroll down to get an autobuild with the latest features.

oh yeah but there is still the wierd pixelation on the sides

**Comment by MrAlaux** [comment]
> oh yeah but there is still the wierd pixelation on the sides

In the latest autobuilds? Are you sure? If so, please share your .cfg so I can test it.

**Comment by KABOM93** [comment]
In the latest autobuilds?

yes, i clicked ot the here link you sent 

and here is the .cfg
[file with my cfg.zip](https://github.com/MrAlaux/Nugget-Doom/files/14612977/file.with.my.cfg.zip)

**Comment by MrAlaux** [comment]
Using your .cfg in the latest master -- that is, [these autobuilds](https://github.com/MrAlaux/Nugget-Doom/actions/runs/8304824461) -- I can't reproduce the issue. It might be because my screen is 768p, so I can't run the game at 2160p like you do.

Let's try something: grab the latest Woof autobuild from [here](https://github.com/fabiangreffrath/woof/actions/runs/8308435049), make a copy of your `nugget-doom.cfg` and rename it to `woof.cfg`, then launch the Woof autobuild using that .cfg. Then, let me know if you see the pixelation on the sides. I want to check if the issue originates in Woof to report it accordingly.

**Comment by KABOM93** [comment]
> Using your .cfg in the latest master -- that is, [these autobuilds](https://github.com/MrAlaux/Nugget-Doom/actions/runs/8304824461) -- I can't reproduce the issue. It might be because my screen is 768p, so I can't run the game at 2160p like you do.
> 
> Let's try something: grab the latest Woof autobuild from [here](https://github.com/fabiangreffrath/woof/actions/runs/8308435049), make a copy of your `nugget-doom.cfg` and rename it to `woof.cfg`, then launch the Woof autobuild using that .cfg. Then, let me know if you see the pixelation on the sides. I want to check if the issue originates in Woof to report it accordingly.

well i think i found the main issue, i tried it in woof and i thought it was not there cuz it didnt look like it but then i looked closer and saw it.so what i think is happening is that nugget dooms res isnt really native but is still 1800p and is lowered to smaller resolutions like your 768p but doesnt go higher than that 1800p witch is a problem with 4k monitors (it also said in nugget that current resolution is 3834x1800 instead of 3840x2160) and well it isnt that noticable in woof and if it was like that in nugget it would be great

**Comment by MrAlaux** [comment]
Nugget's resolution should be working exactly the same as Woof's, I don't recall changing anything.

If you change `default_verbosity` in the .cfg (either Woof's or Nugget's) to `4`, and launch the .com instead of the .exe, the resolution will be reported in the console window. Please verify that both ports are running at the same resolution. Also, please take a screenshot of the error in Woof; you can type `HOM` as a cheat to enable HOM detection, which should make the glitchy columns turn red.

To clarify, neither port is (or should be) running at a 2160px height because of aspect ratio correction; the screen is stretched vertically by x1.2, so `1800 * 1.2 = 2160`. This is completely intentional. As for the 3834px width, that's basically the result of some rounding necessary to make things work properly.

**Comment by MrAlaux** [comment]
Oh, I forgot: the `RATE` cheat also reports the resolution. Please take the Woof screenshot with it enabled.

**Comment by KABOM93** [comment]
oh, so it both runs in the same res the reason i didnt see it in woof was probably because i didnt raise the brightness when i tested woof,so my idea how to fix it (if its possible) is to be able to scale up to 2200p

**Comment by KABOM93** [comment]
keep in mind that im 14 so i dont understand coding that much
