### ISSUE TITLE
Too many .DLL files

### ISSUE THREAD

**Issue by thekovic** [MrAlaux/Nugget-Doom#9]
This might be a bit of a silly complaint but I downloaded Nugget Doom 1.8.0 and I noticed that compared to my 1.6.1 folder, the number of .DLLs starting with the letter L ballooned from 9 to 23 and this started to seriously hamper my ability to drag&drop .WAD files onto nugget-doom.exe. Would you perhaps consider putting the .DLLs into a bin folder or something? :3

**Comment by MrAlaux** [comment]
Greetings!

I agree on that things got rather messy with libraries (DLLs) since last release. As much as I like your idea, I honestly don't know how to get it done; I know nothing about managing dependencies.

Fortunately, I can give you some advice:

Woof changed some of its dependencies recently, which surprisingly added more libraries to go with the executable. However, some of the DLLs used by former versions of Nugget are not necessary anymore, so you may want to look for unused files if your updating method consisted of overwriting your previous installation with the contents of the latest one.

About drag & drop, something that I do with many ports to make it easier is to select the files I want to load, then the .cfg file for the port (which usually has a name identical to the .exe's) and drag from there. On Windows, you can toggle the selection of individual files by holding Ctrl (and maybe holding Shift too) and then Left-Clicking on them.

**Comment by thekovic** [comment]
First of all, thanks for the .cfg tip - didn't know you could drag&drop the .cfg as well.

> you may want to look for unused files if your updating method consisted of overwriting your previous installation with the contents of the latest one.

I downloaded 1.8.0 into a clean folder by extracting the archive from the Releases page which includes the mentioned 23 .DLLs. I tried removing some .DLLs to see if there are some extra but it seems they're all required.

Interestingly though, when I cloned the repository and built Nugget Doom myself (using Visual Studio 2019, building an x64 Release configuration), Nugget Doom built with only 8 .DLLs and everything works fine. I noticed that one of the .DLLs in the current release is called "libwinpthread-1.dll" which seems to be a port of Linux's POSIX threads for Windows. Is it possible that you distributed a "Linux-to-Windows cross-compile" as the win32 release by accident?

**Comment by MrAlaux** [comment]
Well, the latest Woof release, labeled as win32, has that same DLL (surely the same contents apart from the executable, really), so I'm probably doing more or less what Woof's devs do. Assuming that is the case, is either of them a cross build? I couldn't know for sure. I do use MSYS2 for the process, though.

To be completely honest, I don't quite know the theory behind what I do, I just follow a series of steps and get a package that seems to run properly on Windows, unless no one bothered to report issues. It is worth noting that I zip the package and give it the win32 label myself, which could be an ongoing nasty mistake.

**Comment by MrAlaux** [comment]
Any other inquiries, @thekovic?

**Comment by thekovic** [comment]
Well, for me personally the workaround was to just use the copy of Nugget Doom I compiled myself via Visual Studio 2019 which only has 8 .DLLs. I don't know quite enough about the MSYS2 toolchain and how that compiles stuff so I have no idea why the extra .DLLs are needed in your release. So yeah, only thing I can recommend to you or other users at the moment is: Compile with Microsoft's compiler to have fewer .DLLs in the folder. /shrug
